spring:
#  datasource:
#    url: jdbc:mysql://172.16.210.173:3306/auth?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dev-mlas-ins.cx2y4iws05f4.eu-north-1.rds.amazonaws.com:5432/postgres
    username: mlas_user
    password: mlasdb123456
  redis:
    host: 172.16.210.173
    port: 6379
    password: spmiWVD&!BVQ
server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  # 指定 XML 映射文件的路径
  mapper-locations: classpath:mapper/*.xml


